### PR TITLE
Use async/await in samples

### PR DESCRIPTION
**Pull request by JustinBeckwith**
Mostly doing this to start a conversation :) What do y'all think of using async/await in our samples?  I figure, we tell people to start with the latest LTS version of nodejs, which is 8 at this stage 🤷‍♂️  Node.js 6 is 6 months from death, so I don't feel too bad doing this just in the samples. 

Thoughts?

@googleapis/node-team @fhinkel @ace-n

### CODE REVIEW

**Comment by ace-n** [comment]
FWIW the GCF samples include both 6 and 8 (where applicable).

Do we have any relevant data here? (Ping us internally if it's non-public.)

**Comment by ofrobots** [comment]
At this point it makes sense for the samples to assume async/await support. Node 6 will be EOL in April. It is declining in usage (see https://nodejs.org/metrics) and already Node 8 seems be getting 3x the downloads as Node 6.

**Comment by fhinkel** [comment]
Yeah, I think we can start with `async/await` samples.

**Comment by JustinBeckwith** [comment]
@fhinkel what are your thoughts on the way I eliminated the error handling?  We used to console.log the errors, now I am just letting the async method throw.  Is this the pattern we want to roll with for our samples?

**Comment by JustinBeckwith** [comment]
So anyone willing to approve it then? 🤣

**Comment by JustinBeckwith** [comment]
🤷‍♂️ I'll take it

**Pull request merged**
