### PR TITLE
1.1.0

### PR DESCRIPTION
**Pull request by stephenplusplus**
## Features

- (#83): Support an OAUTH access token to be used for all API requests made by this library.

## Fixes

- Many dependency updates for improved performance and reliability.

### CODE REVIEW

**Comment by stephenplusplus** [comment]
@alexander-fenster what am I screwing up here, re: the lint failure?

**Comment by callmehiphop** [comment]
@stephenplusplus I've only seen that error from incorrect package-lock files (I think). You might try regenerating them?

**Comment by stephenplusplus** [comment]
@alexander-fenster @callmehiphop could you give it a try to fix this? I've been using this:

```
npm install
npm link
cd samples
npm link ../
npm install
cd ..
```

And I get

```
/Users/stephen/.nvm/versions/node/v9.8.0/lib/node_modules/@google-cloud/bigquery -> /Users/stephen/dev/nodejs-bigquery
up to date in 7.007s
/Users/stephen/.nvm/versions/node/v9.8.0/lib/node_modules/@google-cloud/bigquery -> /Users/stephen/dev/nodejs-bigquery
/Users/stephen/dev/nodejs-bigquery/samples/node_modules/@google-cloud/bigquery -> /Users/stephen/.nvm/versions/node/v9.8.0/lib/node_modules/@google-cloud/bigquery -> /Users/stephen/dev/nodejs-bigquery
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @google-cloud/bigquery@1.1.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'nodejs-docs-samples-bigquery'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/stephen/.npm/_logs/2018-03-30T11_53_39_590Z-debug.log
```

**Comment by alexander-fenster** [comment]
I found that I need to erase both lock files when I changed anything in package.json (e.g. version, like in this case).  Here is what always worked for me:

```sh
rm -rf node_modules package-lock.json samples/package-lock.json samples/node_modules
npm install && npm link && cd samples && npm link ../ && npm install && cd .. && npm run lint
```

**Pull request merged**
