### PR TITLE
feat: add cross-project support

### LINKED ISSUE #1030: Cross Project Support
Hi, 

We have the dataset in a Project A and would like to run the Bigquery job from Project B. I already shared the Project A dataset to Project B's service account with Data Viewer access. I tested with bq command line and it works as expected. But when I try to run the job using this node module am getting error.
```
User does not have bigquery.jobs.create permission in project A.
```
Is there any workaround to specify the job execution Project ID?.

### PR DESCRIPTION
**Pull request by steffnay**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

Fixes #1030 #527 🦕

### CODE REVIEW

**Comment by satrox28** [comment]
Hi @shollyman,

Can you able to check and approve it. We are eagerly looking for this feature from past few months.

**Review by shollyman — APPROVED** [review]
Do you need more disambiguation for expressing fully qualified references for non-dataset resources like jobs?

**Review by feywind — APPROVED** [review]
LGTM

**Comment by satrox28** [comment]
Can it be merged, any pending?

**Pull request merged**
