### PR TITLE
Added support for the NUMERIC values.

### PR DESCRIPTION
**Pull request by aprgoog**
This change adds support for the newly added NUMERIC data type to the nodejs BigQuery library.

### CODE REVIEW

**Comment by JustinBeckwith** [comment]
Good question for @googleapis/node-team :)

**Comment by ofrobots** [comment]
What's the forward compatibility story with the core [BigInt](https://developers.google.com/web/updates/2018/05/bigint) language feature that we just shipped with Node 10?

**Comment by tswast** [comment]
@ofrobots Do BigInts support fractional values?

**Comment by ofrobots** [comment]
It does not. I've removed the block. Will take a deeper look later.

**Comment by ofrobots** [comment]
For posterity here is a link to the BigQuery docs on the NUMERIC data type: https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#numeric-type

**Comment by stephenplusplus** [comment]
LGTM, but we should probably have a system test for this new type.

**Comment by aprgoog** [comment]
@stephenplusplus Added a system test, please take another look.

**Comment by aprgoog** [comment]
Can somebody merge the changes? I do not have write access to the repo.

**Comment by nikhilag** [comment]
I upgraded the bigquery node js library aftera long time and my app broke because of numeric values being returned as Big() values. Is it possible for me to have the existing behaviour where I got the numeric result back as string? I am storing the query result in firestore which won't support Big() and converting the results manually to string seems tedious. Is there any query option one can use to disable this new behaviour?

**Pull request merged**
