### PR TITLE
feat: Allow setting BigQuery Job labels in createQueryJob method

### LINKED ISSUE #863: Support Job labels
**Is your feature request related to a problem? Please describe.**
BQ JobConfiguration API objects have labels (https://cloud.google.com/bigquery/docs/reference/rest/v2/Job#JobConfiguration). I'd like to be able to set them using this client library.

 **Describe alternatives you've considered**
I don't think there are alternatives beyond (a) using a different language or (b) issuing raw API requests.

 **Additional context**
I'm happy to contribute this change. As per https://github.com/googleapis/nodejs-bigquery/blob/master/CONTRIBUTING.md I'm filing an issue explaining the change.

I suggest implementing this in much the same way as `dryRun`:
- the `Query` type would have a new field `labels: { [label: string]: string }`: https://github.com/googleapis/nodejs-bigquery/blob/1e56383da5/src/bigquery.ts#L87
- this would be passed through to the final `Job` in exactly the same way as `dryRun`: https://github.com/googleapis/nodejs-bigquery/blob/1e56383da5/src/bigquery.ts#L1254

I'm happy to make this change, as per https://github.com/googleapis/nodejs-bigquery/blob/master/CONTRIBUTING.md are you folks happy with me sending a PR?

### PR DESCRIPTION
**Pull request by BenBirt**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/nodejs-bigquery/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

Fixes https://github.com/googleapis/nodejs-bigquery/issues/863 🦕

Notes:
- I wasn't able to run `npm run samples-test`; it throws an error complaining about missing `chai`, is this expected to be installed globally?
- `npm run fix` similarly shows many `node/no-missing-require` errors complaining about missing packages; I've no idea why this happens.

### CODE REVIEW

**Comment by BenBirt** [comment]
@googlebot I signed it!

**Comment by stephenplusplus** [comment]
Thank you, this looks good to me! Would you mind adding a line in the JSDocs block above the method to describe the new option?

**Comment by BenBirt** [comment]
@stephenplusplus done!

**Review by stephenplusplus — APPROVED** [review]

**Comment by BenBirt** [comment]
@stephenplusplus what's the process for getting this merged?

**Comment by stephenplusplus** [comment]
Thank you for a very pleasant issue-to-PR-to-merge experience from this side! Feel free to stop by anytime :)

**Comment by stephenplusplus** [comment]
> what's the process for getting this merged?

Merged now, and I'll release in https://github.com/googleapis/nodejs-bigquery/pull/866 once all those checks pass. After that, a bot auto-releases. ETA of release to npm, within an hour.

**Comment by BenBirt** [comment]
Thanks a lot for the quick turnaround! Very pleasant experience on my end too.

**Comment by stephenplusplus** [comment]
The new release is out under 5.3.0. 🍻

**Pull request merged**
