### PR TITLE
more description for nextQuery

### PR DESCRIPTION
**Pull request by alexander-fenster**
Please check if the update is valid.

### CODE REVIEW

**Comment by stephenplusplus** [comment]
Is this true? I would think the API returns some, but not all, rows in each API response.

**Comment by alexander-fenster** [comment]
@stephenplusplus That was the suggested edit by the API owners. As I understand, what it's supposed to say is that if the query has not started returning any rows–i.e. is incomplete,–the rows array might be empty, with non-null nextQuery. Do you have any suggestions how it can be written better?

**Comment by stephenplusplus** [comment]
I guess the question would be if the [getQueryResults API](https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs/getQueryResults) ever returns `pageToken` but an empty `rows`. I didn't think that situation could occur, but if the API team confirms that it can, then the edits in this PR are perfect.

**Comment by stephenplusplus** [comment]
Looks like there's another property in the picture, `jobComplete`:

> **jobComplete** If rows or totalRows are present, this will always be true

So, it sounds like rows could be empty and `jobComplete` can be false, meaning we'll execute the callback with an empty array for rows, just like the API team said :) Sorry for the delay. Let's merge this thing.

**Pull request merged**
